CREATE CATALOG IF NOT EXISTS main;
CREATE SCHEMA IF NOT EXISTS main.heqp;
CREATE VOLUME IF NOT EXISTS main.heqp.bronze;
CREATE VOLUME IF NOT EXISTS main.heqp.checkpoints;
CREATE VOLUME IF NOT EXISTS main.heqp.silver;